### ISSUE TITLE
Update Copy on the Bubble Graphic

### ISSUE THREAD

**Issue by brendonsanctuary** [sanctuarycomputer/negative#18]
We finally got the right info for the bubble graphic! 

It is in the designs as well :)

<img width="464" alt="Screen Shot 2020-07-15 at 12 02 20 PM" src="https://user-images.githubusercontent.com/58054507/87570342-7f381f80-c696-11ea-9dfa-698059106d3b.png">

**Comment by chrismekim** [comment]
Closed by #19
