### ISSUE TITLE
Helping Clients: Greenland Image 1280++

### ISSUE THREAD

**Issue by brendonsanctuary** [sanctuarycomputer/negative#34]
On the large desktop can we move the "Greenland" image and caption more to the left. I turned off the margin-left to get the image in this position.

<img width="272" alt="Screen Shot 2020-07-21 at 11 32 35 AM" src="https://user-images.githubusercontent.com/58054507/88074824-ed249100-cb45-11ea-9ded-8b2d58862c02.png">

<img width="1859" alt="Screen Shot 2020-07-21 at 11 31 26 AM" src="https://user-images.githubusercontent.com/58054507/88074726-c6665a80-cb45-11ea-9ac5-3081722bc7fa.png">

**Comment by chrismekim** [comment]
Right now the design shows it as offset by 4 columns. Should I offset by 2 columns instead? Or 3?

**Comment by brendonsanctuary** [comment]
2-col with a 2-col offset.
