### ISSUE TITLE
Animations

### ISSUE THREAD

**Issue by brendonsanctuary** [sanctuarycomputer/negative#52]
•	There’s a bit too much “up and in”. Every block seems to slide up as it fades in, which feels way extra to me. Thoughts?
_Just remove the upward movement and make it fade in_

•	The hero animations feel little stiff. I think some small tweaks to the easing of the big lettering to make them a bit more graceful would go a long way.
_if we make the position a little longer distance for each section and add one of the easings https://easings.net/#easeInOutQuad or https://easings.net/#easeInOutCubic_

•	Closing the menu is slow to rollback the backdrop. Feels like the backdrop exiting could be snappier and more a part of the text exiting
_We should mimic the speed of how the gradient opens_

•	The drop and in for the menu text also feels kinda stiff. Can we stagger in the the links?
_Good example of stagger https://www.brinkerhoffpoetry.org/_

•	I also feel the “drop” for the main page as the menu opens is a bit stiff and blocky. Any ideas there?
_We can increase the distance of the "drop" and add one of the easing curves from above._

**Comment by chrismekim** [comment]
@brendonsanctuary Thanks! :) I'm going to combine this one with the other issue about animations #39 !
