### ISSUE TITLE
On Mobile: Diagrams and Diagram captions should take up content width

### ISSUE THREAD

**Issue by hhff** [sanctuarycomputer/negative#55]
IMO, this kinda looks like a mistake:

Thoughts @brendonsanctuary ?
![image](https://user-images.githubusercontent.com/2865404/88210645-832de980-cc22-11ea-9dd2-44bd56d42012.png)

**Comment by brendonsanctuary** [comment]
@chrismekim If we could just get the caption to be full width of the diagram and content. 
@hhff if you could elaborate.

**Comment by hhff** [comment]
@brendonsanctuary this is more of a nitpick than anything. Just feels to me when I scroll on my phone that this image should be centered in the page. Happy for it to be ignored :)

**Comment by brendonsanctuary** [comment]
Doesn't bother me but we should just make sure they flow inline with the copy.

@chrismekim 

Let's just make sure all diagrams on mobile are full content width ( not full screen width) and have their corresponding captions full content width. 

Diagrams
A.: Increase caption width
B. Alignment needs to match up with content width on the diagram and the list below it.
D. Caption width





<img width="527" alt="Screen Shot 2020-07-22 at 2 55 22 PM" src="https://user-images.githubusercontent.com/58054507/88216706-7792f080-cc2b-11ea-941c-84da28d12431.png">





<img width="383" alt="Screen Shot 2020-07-22 at 2 54 52 PM" src="https://user-images.githubusercontent.com/58054507/88216704-76fa5a00-cc2b-11ea-9db9-b743fe7139b3.png">
