### ISSUE TITLE
Should the Globe be above the "Carbon Negative" text on the homepage hero?

### ISSUE THREAD

**Issue by hhff** [sanctuarycomputer/negative#58]
@brendonsanctuary I remember we were planning that the chunks of the globe would be over the text. That doesn't seem to be the case currently - is that by design?

**Comment by brendonsanctuary** [comment]
Fixed in a PR

**Comment by chrismekim** [comment]
It was fixed in this PR (https://peek.run/61mhgwm9) but this change is not showing up in the production branch for some reason... looking into it!

**Comment by chrismekim** [comment]
Cleared my cached data and cookies and am now seeing this update! Closed by #36
